### ISSUE TITLE
i tried python3 instracker.py -u 'new_account' -t 'main_account'

### ISSUE THREAD

**Issue by AyaanMAG** [andrea-varesio/instracker#2]
it didnt work, i have the same bug as [https://github.com/andrea-varesio/instracker/issues/1](url)

**Comment by andrea-varesio** [comment]
Just to confirm, did you include the quotation marks ?

This seems to be an upstream issue unfortunately, though I'm not getting any errors. Would you mind sharing some more details ? (OS, Python version, and whether or not the usernames you've used include special characters)

**Comment by AyaanMAG** [comment]
I did, since some of this info might be sensative can i personally message you somehow? I'll send you a screen recording in about 13 hours if that will help

**Comment by andrea-varesio** [comment]
Sure, but I don't need anything sensitive or personally identifiable. No screen recording is necessary.

It would help to know the exact error message; if you don't want to send it, you could compare it with issue #1 and let me know if it's the same.

**Comment by AyaanMAG** [comment]
![Screenshot_11](https://user-images.githubusercontent.com/63659414/161870805-8722bd51-df4a-4282-b15e-9734f4bf4739.png)

**Comment by andrea-varesio** [comment]
Since the [instagram_scraper](https://github.com/realsirjoe/instagram-scraper) dependency is no longer being developed, this repository will be archived.
